Charles/caption float
tollbros/tollbrothers-ui pull request #72
Opened 2024-05-09 20:05 UTC by chaznied

## JIRA Ticket
[https://tbnextjs.atlassian.net/browse/NJP-2114]

## Describe Changes in this Pull Request

- Updated caption styles in fullscreen for video/images/daf images

## Testing Instructions

- Pull this from the tollbrothers-ui repo [https://github.com/tollbros/tollbrothers-ui/tree/charles/captionFloat]
- Run `npm run start`
- Pull this from the tollbrothers.com repo [https://bitbucket.org/tollbrothers/com.tollbrothers.www/branch/charles/NJP-2114-tollbrothers-ui-advantage-page-]
- Update `package.json` with `"@tollbrothers/tollbrothers-ui": "file:../tollbrothers-ui",`
- Run `npm i`
- Run `npm run dev`
- Test here - [http://localhost:3000/advantage]
- Test Daf images here - [http://localhost:3000/luxury-homes-for-sale/California/Skylar-by-Toll-Brothers/Quick-Move-In/261420]
- Test randomly here - [http://localhost:3000/luxury-homes-for-sale/New-Jersey/Canter-Square/Mueller]

## Screen Shot(s)/Video(s) of Working Changes
Please add screen shots or screen recordings showing the changes

### Tasks:

1. [ ] Changes Meet JIRA Tickets Requirements
2. [ ] Commit message with `fix` or `feat` to trigger new release
3. [ ] Tested changes on Mobile, Tablet and Desktop screen sizes
4. [ ] Tested changes on Chrome, FireFox and Safari
5. [ ] Demoed to Design Team (For new features only)
6. [ ] Notified Digital Marketing Team if changes will impact A/B Tests
7. [ ] Checked Tracking/Analytics (Notified Digital Marketing Team if changes impact tracking)

2024-05-15 18:44 UTC, cormdog commented
Needs a little tweaking on mobile. Screenshot attached.
![IMG_0564](https://github.com/tollbros/tollbrothers-ui/assets/2752502/49d137a2-614d-4a8d-a557-5bd37b6357e3)

2024-05-15 20:40 UTC, mikeduarte requested changes
Left a few comments

2024-05-15 20:40 UTC, mikeduarte commented on src/components/FullScreenGallery.module.scss
> +        object-fit: cover;
This causes a really big change to the tb.com gallery, especially on mobile. We might want to get input from Justin.

Before:
![Screenshot 2024-05-15 at 4 32 16 PM](https://github.com/tollbros/tollbrothers-ui/assets/15040013/0562d564-6d98-403e-82a6-b8558aee1c6d)


Your Branch:
![Screenshot 2024-05-15 at 4 32 09 PM](https://github.com/tollbros/tollbrothers-ui/assets/15040013/9e115b9a-6f41-4eec-987f-02563911a1a5)

2024-05-15 20:40 UTC, mikeduarte commented on src/components/GalleryMedia.js
> +  isDesignerAppointed
I don't think this is being use.

2024-05-15 20:40 UTC, mikeduarte commented on src/components/FullScreenGallery.js
> +  isDesignerAppointed
Similar to the other PR, we might want to pass a classes prop from the parent app to override styles here. We can huddle about it.

2024-05-21 17:25 UTC, chaznied commented
@mikeduarte  - updated, only adjusting captions for videos/walkthrough above 768 and added class prop

2024-05-28 15:36 UTC, Chenzo commented
Hey, per our conversation, fix this from floating over the controls (via Justin's fix of removing all that from any video)

![Screenshot 2024-05-28 at 11 35 43 AM](https://github.com/tollbros/tollbrothers-ui/assets/505404/bf888192-b942-4bcb-94ec-2830dd510dae)

2024-05-28 15:37 UTC, Chenzo requested changes
see my previous comment

2024-05-28 18:07 UTC, chaznied commented
@Chenzo , @mikeduarte  - I just remembered we can't remove captions from any video because of the disclaimer i had to add for all inside maps...

2024-05-28 19:38 UTC, chaznied commented
@Chenzo , @mikeduarte  - Updated GalleryMedia.js to only show captions for images and insidemaps walkthroughs and removing counter and social from videos and walkthroughs

2024-05-29 15:55 UTC, mikeduarte requested changes

2024-05-29 15:55 UTC, mikeduarte commented on src/components/GalleryMedia.js
> +    customClass = styles.mediaVideo
Do we need this if we aren't showing captions on videos?

2024-05-29 15:55 UTC, mikeduarte commented on src/components/FullScreenGallery.module.scss
> +          object-fit: cover;
I don't think we need this. I don't see a difference when I comment it out.

2024-05-29 15:55 UTC, mikeduarte commented on src/components/GalleryMedia.js
> +    customClass = styles.mediaVideo
Maybe this should only get applied if there is a caption and showCaption is true?

2024-06-01 15:01 UTC, mikeduarte approved these changes

2024-06-03 12:13 UTC, chaznied commented
@Chenzo  - I kept the caption for inside maps (legal) and walkthroughs (Justin) and images, removed captions from videos (Justin), removed social/counter from video and walkthroughs (Justin). Images remain the same

2024-06-03 16:04 UTC, Chenzo commented
Matterports don't seem to work. We chatted. Waiting on fix.

2024-06-03 21:18 UTC, Chenzo approved these changes
It's totally something from Matterport in either your cookies, session or local storage.

2024-06-03 21:18 UTC, merged

2024-06-03 21:19 UTC, sarameix commented
:tada: This PR is included in version 1.21.1 :tada:

The release is available on:
- [npm package (@latest dist-tag)](https://www.npmjs.com/package/@tollbrothers/tollbrothers-ui/v/1.21.1)
- [GitHub release](https://github.com/tollbros/tollbrothers-ui/releases/tag/v1.21.1)

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket: